---

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-xml
  - id: check-added-large-files
  - id: no-commit-to-branch
  - id: check-merge-conflict
  - id: double-quote-string-fixer
  - id: requirements-txt-fixer
  - id: check-docstring-first
  - id: name-tests-test
    args:
    - --django
  - id: check-ast
  - id: debug-statements

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/pylint
  rev: v3.3.3
  hooks:
  - id: pylint
    args:
    - --django-settings-module=mysite.settings
    additional_dependencies:
    - coverage
    - django==3.2.25
    - pylint-django >= 2.6.1

- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-cognitive-complexity ~= 0.1.0
    - flake8-docstrings == 1.7.0

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.33.0
  hooks:
  - id: yamllint
    args:
    - --strict
